import Script from "next/script"
import Header from "./components/Header/Header"
import './global.sass'
import Footer from "./components/Footer/Footer"
import 'react-phone-number-input/style.css'
import dynamic from 'next/dynamic'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const NoSSRHeader = dynamic(() => import('./components/Header/Header'), { ssr: false })
  return (
    <html lang="en">
      <body>
        <NoSSRHeader/>
        {children}
        <Footer/>
        <Script src="https://kit.fontawesome.com/073ad96d9b.js" crossorigin="anonymous"></Script>
      </body>
    </html>
  )
}
